package com.ysl.enums;

public enum EventMessageType {
    SHORT_LINK_ADD,
    SHORT_LINK_ADD_LINK,
    SHORT_LINK_ADD_MAPPING,

    SHORT_LINK_DEL,
    SHORT_LINK_DEL_LINK,
    SHORT_LINK_DEL_MAPPING,


    SHORT_LINK_UPDATE,
    SHORT_LINK_UPDATE_LINK,
    SHORT_LINK_UPDATE_MAPPING,
}
